// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tysjyccoukblpioqntcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5c2p5Y2NvdWtibHBpb3FudGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzA0NDksImV4cCI6MjA2ODY0NjQ0OX0.qepLilrOFuTnOcWQlorsluT03H5Bj88pTXMsw_DVTI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});